# Generated by Django 4.2.1 on 2023-05-19 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars_model', models.CharField(max_length=30, verbose_name='Модель машины')),
            ],
            options={
                'verbose_name': 'Модели машин',
                'verbose_name_plural': 'Модели машин',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_order', models.DateField(verbose_name='Дата заказа')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_dealership.carsmodels', verbose_name='Модель машины')),
            ],
            options={
                'verbose_name': 'Заказчик и дата',
                'verbose_name_plural': 'Заказчики и даты заказа',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('ser_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('patronymiс', models.CharField(max_length=30, verbose_name='Отчество')),
                ('city', models.CharField(max_length=20, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Список людей',
                'verbose_name_plural': 'Список людей',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_work', models.CharField(max_length=50, verbose_name='Вид услуги')),
                ('price', models.IntegerField(help_text='цена в BYN', verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Вид услуги в СТО',
                'verbose_name_plural': 'Виды услуг в СТО',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_dealership.customers', verbose_name='Заказчик')),
                ('works', models.ManyToManyField(to='car_dealership.works', verbose_name='Виды работ')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='customers',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_dealership.people', verbose_name='Заказчик'),
        ),
    ]
